[package]
authors = ["brad"]
name = "quick_main"
version = "0.1.0"

[[bin]]
doc = false
name = "quick_main"
path = "src/bin/quick_main/bin.rs"
test = false

[dependencies]
assayer = "0.2.2"
error_def = "0.3.15"
libc = "0.2.31"

[lib]
name = "quick_main"
path = "src/lib/quick_main.rs"
